name: Auto Pull Request

on:
  push:
    branches:
      - '*'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Automated Pull Request from ${{ github.ref_name }}"
          branch: ${{ github.ref_name }}
          base: master # Hedef branch
          title: "Automated Pull Request for ${{ github.ref_name }}"
          body: "This is an automated pull request created by GitHub Actions."
